### ISSUE TITLE
Missing "Next" and "Previous" arrows.

### ISSUE THREAD

**Issue by LittleLukas** [rvpatel/Magento-Special-Product-Module#5]
Hello,

After install on the sale page shows for example:  Items 1 to 12 of 23 total  .By default show 12 item per page missing arrow "Next" or "Previous" to see more. 

Thank you.

**Comment by rvpatel** [comment]
Using this code work with pagination

{{block type="pws_special/catalog_product_list" toolbar_block_name="product_list_toolbar" template="catalog/product/list.phtml"}}

**Comment by LittleLukas** [comment]
Hello,

Nothing changed. Still the same. The toolbar and previously been showing but at the bottom and top of the page should to be arrows  next or previous page.

See the link  http://www.littlelukas.com/on-sale-special-price http://www.littlelukas.com/on-sale-special-price

And here how should to be :  http://www.littlelukas.com/everything-for-your-bedroom/cotton-bedding.html http://www.littlelukas.com/everything-for-your-bedroom/cotton-bedding.html

Gediminas

Thank you

LittleLukas

Find Us On:  https://www.facebook.com/littlelukas2011 social_facebook_box_blue_16  https://plus.google.com/+Littlelukas/posts google-plus  https://twitter.com/Little_Lukas social_twitter_box_blue_16  http://www.pinterest.com/littlelukas/ pinterest-16x16  https://www.youtube.com/channel/UCPHy9A_1-lzfjd8yAW8Tk3w 1362896765_youtube  http://www.linkedin.com/company/littlelukas/ linkedin

 http://www.littlelukas.com/ banner

The contents of this email may be confidential. If you have received this email in error please inform the sender and delete this email. Any comments expressed are those of the author and may be reflective of The Company’s view.

**Comment by rvpatel** [comment]
Thanks, for interest and reply.
Now this code develop and implement for one site there have work very well.

Please send data about your site which theme u use or other details. 
Please contact me on my email address for magento & wordpress issue.

**Comment by LittleLukas** [comment]
Hello,

Thank you for your respond. Please see the link  http://www.littlelukas.com/on-sale-special-price http://www.littlelukas.com/on-sale-special-price . Missing arrows.

Here is the link for sample to see how should be  http://www.littlelukas.com/everything-for-your-bedroom/cotton-bedding.html http://www.littlelukas.com/everything-for-your-bedroom/cotton-bedding.html

We are using magento 1.9.1.0 and  http://themeforest.net/item/fortis-responsive-magento-theme/1744309?WT.ac=search_item&WT.oss_phrase=fortis&WT.oss_rank=1&WT.z_author=infortis Fortis theme.

Gediminas

**Comment by rvpatel** [comment]
See i have implement on lattest version of magento. 1.9.1.0.
![pws-1](https://cloud.githubusercontent.com/assets/5517932/7101215/b88415d6-e06a-11e4-8ab2-a4bc9740e99c.png)
![pws-2](https://cloud.githubusercontent.com/assets/5517932/7101216/c1e69194-e06a-11e4-9142-0dc43814b961.png)
![pws-3](https://cloud.githubusercontent.com/assets/5517932/7101217/c219a034-e06a-11e4-8a57-a82d2eaef374.png)

U have also use this code direct on page.

U have use a theme so how to check this is compatible or not if any suggestion then i will send u..
if possible to send me your your theme on my mail?  

Are u developer? or site owner.
